# NOTE: ORDER MATTERS HERE... this is listed in priority order, if order is changed, household_distributor logic may also need to be changed.
default_household_compositions:
  "0 0 0 2":
    labels: "Single family household: All aged 66 years and over"
    composition: [ 0, 0, 0, 0, 2 ]
    household: "old"
    size: 2

  "0 0 2 0":
    labels: [ "Single family household: Married or civil partnership couple: No children",
              "Single family household: Cohabiting couple family: No children" ]
    composition: [ 0, 0, 0, 2, 0 ]
    household: "nokids"
    size: 2

  "0 0 0 1":
    labels: "One-person household: Aged 66 years and over"
    composition: [0, 0, 0, 0, 1]
    household: "old"
    size: 1

  "0 0 1 0":
    labels: "One-person household: Other"
    composition: [0, 0, 0, 1, 0]
    household: "nokids"
    size: 1

  ">=1 >=0 2 0":
    labels: ["Single family household: Married or civil partnership couple: Dependent children",
      "Single family household: Cohabiting couple family: With dependent children"]
    composition: [1.5, 0.5, 0.5, 2, 0]
    household: "d_family"
    size: 3.5

  "0 >=1 2 0":
    labels: ["Single family household: Married or civil partnership couple: All children non-dependent",
      "Single family household: Cohabiting couple family: All children non-dependent"]
    composition: [ 0, 1.5, 0.5, 2, 0]
    household: "nd_family"
    size: 3.5

  ">=1 >=0 1 0":
    labels: "Single family household: Lone parent family: With dependent children"
    composition: [1.5, 0.5, 0.5, 1, 0]
    household: "d_family"
    size: 2.5

  "0 >=1 1 0":
    labels: "Single family household: Lone parent family: All children non-dependent"
    composition: [0, 1.5, 0.5, 1, 0]
    household: "nd_family"
    size: 2.5

  "0 >=0 >=0 >=0":
    labels: "Other household types: Other related household: Other family composition"
    composition: [0, 0.5, 0.5, 0.5, 0.5]
    household: "other"
    size: 2.5

  ">=1 >=0 >=0 >=0":
    labels: "Other household types: With dependent children"
    composition: [1.5, 0.5, 0.5, 0.5, 0.5]
    household: "other"
    size: 2.5

  "0 >=0 0 >=0":
    labels: "Other household types: Other, including all full-time students and all aged 66 years and over"
    composition: [0, 0, 0.5, 0, 0.5]
    household: "other"
    size: 2.5
